# -*- coding: utf-8 -*-
"""Chat Bot AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nipqT5xf6dLm_k6J3Arl1-Jrni5U2qF2
"""

import random
import nltk

BOT_CONFIG = {
    "intents" : {
        "hello" : {
            "examples" : ["привет!", "здорово", "хай!", "здравствуй", "добрый день", "хэллоу", "здравия желаю"],
            "responses" : ["Хэллоу)", "Хай!", "Приветствую...", "Здравствуй :)"] 
        },
        "buy" : {
            "examples" : ["пока", "до свидания", "увидимся", "удачи!"],
            "responses" : ["Пока))", "Увидимся!", "Успехов!", "Сайонара"] 
        }
    },

    "not understand" : ["Я вас не понимаю", "Nicht comprende", "Выражайтесь яснее", "Не очень понятно, что вы сказали",
                        "Можете перефразировать ваше сообщение?"]
}

def clean_text(text):
  result = ""
  for letter in text:
    letter = letter.lower()
    if letter in "абвгдеёжзийклмнопрстуфхцчшщъыьэюя":
      result += letter
  return result

def search_intent(text):
  text = clean_text(text)
  for intent in BOT_CONFIG["intents"]:
    for example in BOT_CONFIG["intents"][intent]["examples"]:
      example = clean_text(example)
      if nltk.edit_distance(text, example) / max(len(text), len(example)) < 0.5:
        return intent
  return "unknown intent"

def chat_bot():
  user_text = ""
  while user_text != "стоп":
    user_text = clean_text(input())
    if user_text != "стоп":
      intent = search_intent(user_text)
      if intent != "unknown intent":
        bot_text = random.choice(BOT_CONFIG["intents"][intent]["responses"])
        print(bot_text)
      else:
        print(random.choice(BOT_CONFIG["not understand"]))

chat_bot()